from __future__ import annotations
from bus import Bus
from dataclasses import dataclass
from fixed_types import uint16, uint8, check_type
from enum import IntEnum
from typing import Callable, List

@dataclass
class Instruction:
    name:       str
    cycle:      uint8
    operate:    Callable[[], uint8]
    addrmode:   Callable[[], uint8]

class FLAGS(IntEnum):
    C = (1 << 0)    # Carry Bit
    Z = (1 << 1)    # Zero 
    I = (1 << 2)    # Disable Interrupts
    D = (1 << 3)    # Decimal Mode (unused in )
    B = (1 << 4)    # Break
    U = (1 << 5)    # Unused
    V = (1 << 6)    # Overflow
    N = (1 << 7)    # Negative

class CPU_6502(object):
    def __init__(self):
        self.a = uint8(0x00)            # Accumulator register
        self.x = uint8(0x00)            # X register 
        self.y = uint8(0x00)            # Y register 
        self.stkp = uint16(0x00)        # Stack Pointer 
        self.pc = uint16(0x00)          # Program Counter
        self.status = uint8(0x00)       # status register

        self.fetched = uint8(0x00)      # current fetched data
        self.addr_addr = uint16(0x0000) # can be used to read from diff location of memory.
        self.addr_rel = uint16(0x0000)  # used for branching, to jump a certain amount of distance
        self.opcode = uint8(0x00)       # current opcode
        self.cycles = uint8(0x00)       # stores the number of cycles left for the current instruction.
        self.lookup: List[Instruction] = self.generate_table()

    def connect_bus(self, bus: Bus) -> None:
        # connect cpu to bus
        check_type(bus, Bus)
        self.bus = bus
    
    def read(self, addr: uint16) -> uint8:
        # read from bus
        check_type(addr, uint16)
        return self.bus.read(addr, False)

    def write(self, addr: uint16, val: uint8) -> None:
        # write to bus
        check_type(val, uint8)
        self.bus.write(addr, val)
    
    def get_flag(f: FLAGS) -> uint8: ...

    def set_flag(f: FLAGS, value: bool) -> None:
        # set bits in status register depending on flag
        ...
    
    # Adressing Modes 
    def imp(self) -> uint8: ...
    def imm(self) -> uint8: ...
    def zp0(self) -> uint8: ...
    def zpx(self) -> uint8: ...
    def zpy(self) -> uint8: ...
    def rel(self) -> uint8: ...
    def abs(self) -> uint8: ...
    def abx(self) -> uint8: ...
    def aby(self) -> uint8: ...
    def ind(self) -> uint8: ...
    def izx(self) -> uint8: ...
    def izy(self) -> uint8: ...

    # Opcodes
    def adc(self) -> uint8: ...
    def _and(self) -> uint8: ...
    def asl(self) -> uint8: ...
    def bcc(self) -> uint8: ...
    def bcs(self) -> uint8: ...
    def beq(self) -> uint8: ...
    def bit(self) -> uint8: ...
    def bmi(self) -> uint8: ...
    def bne(self) -> uint8: ...
    def bpl(self) -> uint8: ...
    def brk(self) -> uint8: ...
    def bvc(self) -> uint8: ...
    def bvs(self) -> uint8: ...
    def clc(self) -> uint8: ...
    def cld(self) -> uint8: ...
    def cli(self) -> uint8: ...
    def clv(self) -> uint8: ...
    def cmp(self) -> uint8: ...
    def cpx(self) -> uint8: ...
    def cpy(self) -> uint8: ...
    def dec(self) -> uint8: ...
    def dex(self) -> uint8: ...
    def dey(self) -> uint8: ...
    def eor(self) -> uint8: ...
    def inc(self) -> uint8: ...
    def inx(self) -> uint8: ...
    def iny(self) -> uint8: ...
    def jmp(self) -> uint8: ...
    def jsr(self) -> uint8: ...
    def lda(self) -> uint8: ...
    def ldx(self) -> uint8: ...
    def ldy(self) -> uint8: ...
    def lsr(self) -> uint8: ...
    def nop(self) -> uint8: ...
    def ora(self) -> uint8: ...
    def pha(self) -> uint8: ...
    def php(self) -> uint8: ...
    def pla(self) -> uint8: ...
    def plp(self) -> uint8: ...
    def rol(self) -> uint8: ...
    def ror(self) -> uint8: ...
    def rti(self) -> uint8: ...
    def rts(self) -> uint8: ...
    def sbc(self) -> uint8: ...
    def sec(self) -> uint8: ...
    def sed(self) -> uint8: ...
    def sei(self) -> uint8: ...
    def sta(self) -> uint8: ...
    def stx(self) -> uint8: ...
    def sty(self) -> uint8: ...
    def tax(self) -> uint8: ...
    def tay(self) -> uint8: ...
    def tsx(self) -> uint8: ...
    def txa(self) -> uint8: ...
    def txs(self) -> uint8: ...
    def tya(self) -> uint8: ...

    def xxx(self) -> uint8: ... 

    # external signals
    def clock(self) -> None: 
        # one clock cycle to occur
        ...
    # reset, irq, nmi can occur at anytime
    # need to behave async.
    # interrupts processor from doing what it is currently doing. 
    # only finishing current instruction
    def reset(self) -> None: ...
    def irq(self) -> None:
        # interrupt request signal
        # can be ignored depeninding if the interrupt enable flag is set
        ...
    def nmi(self) -> None: 
        # non maskable interrupt request signal
        ...

    def fetch(self) -> uint8:
        # fetch data from apporpriate source
        ...
    
    def generate_table(self) -> List[Instruction]:
        instruction_list = List[Instruction] = [
            Instruction("BRK", self.brk, self.imm, 7), Instruction("ORA", ORA, self.izx, 6), Instruction("???", self.xxx, self.imp, 2), Instruction("???", self.xxx, self.imp, 8), Instruction("???", NOP, self.imp, 3), Instruction("ORA", ORA, self.zp0, 3), Instruction("ASL", ASL, self.zp0, 5), Instruction("???", self.xxx, self.imp, 5), Instruction("PHP", PHP, self.imp, 3), Instruction("ORA", ORA, self.imp, 2), Instruction("ASL", ASL, self.imp, 2), Instruction("???", self.xxx, self.imp, 2), Instruction("???", NOP, self.imp, 4), Instruction("ORA", ORA, self.abs, 4), Instruction("ASL", ASL, self.abs, 6), Instruction("???", self.xxx, self.imp, 6),
            Instruction("BPL", self.bpl, self.rel, 2), Instruction("ORA", ORA, self.izy, 5), Instruction("???", self.xxx, self.imp, 2), Instruction("???", self.xxx, self.imp, 8), Instruction("???", NOP, self.imp, 4), Instruction("ORA", ORA, self.zpx, 4), Instruction("ASL", ASL, self.zpx, 6), Instruction("???", self.xxx, self.imp, 6), Instruction("CLC", CLC, self.imp, 2), Instruction("ORA", ORA, self.aby, 4), Instruction("???", NOP, self.imp, 2), Instruction("???", self.xxx, self.imp, 7), Instruction("???", NOP, self.imp, 4), Instruction("ORA", ORA, self.abx, 4), Instruction("ASL", ASL, self.abx, 7), Instruction("???", self.xxx, self.imp, 7),
            Instruction("JSR", self.jsr, self.abs, 6), Instruction("AND", AND, self.izx, 6), Instruction("???", self.xxx, self.imp, 2), Instruction("???", self.xxx, self.imp, 8), Instruction("BIT", BIT, self.zp0, 3), Instruction("AND", AND, self.zp0, 3), Instruction("ROL", ROL, self.zp0, 5), Instruction("???", self.xxx, self.imp, 5), Instruction("PLP", PLP, self.imp, 4), Instruction("AND", AND, self.imp, 2), Instruction("ROL", ROL, self.imp, 2), Instruction("???", self.xxx, self.imp, 2), Instruction("BIT", BIT, self.abs, 4), Instruction("AND", AND, self.abs, 4), Instruction("ROL", ROL, self.abs, 6), Instruction("???", self.xxx, self.imp, 6),
            Instruction("BMI", self.bmi, self.rel, 2), Instruction("AND", AND, self.izy, 5), Instruction("???", self.xxx, self.imp, 2), Instruction("???", self.xxx, self.imp, 8), Instruction("???", NOP, self.imp, 4), Instruction("AND", AND, self.zpx, 4), Instruction("ROL", ROL, self.zpx, 6), Instruction("???", self.xxx, self.imp, 6), Instruction("SEC", SEC, self.imp, 2), Instruction("AND", AND, self.aby, 4), Instruction("???", NOP, self.imp, 2), Instruction("???", self.xxx, self.imp, 7), Instruction("???", NOP, self.imp, 4), Instruction("AND", AND, self.abx, 4), Instruction("ROL", ROL, self.abx, 7), Instruction("???", self.xxx, self.imp, 7),
            Instruction("RTI", self.rti, self.imp, 6), Instruction("EOR", EOR, self.izx, 6), Instruction("???", self.xxx, self.imp, 2), Instruction("???", self.xxx, self.imp, 8), Instruction("???", NOP, self.imp, 3), Instruction("EOR", EOR, self.zp0, 3), Instruction("LSR", LSR, self.zp0, 5), Instruction("???", self.xxx, self.imp, 5), Instruction("PHA", PHA, self.imp, 3), Instruction("EOR", EOR, self.imp, 2), Instruction("LSR", LSR, self.imp, 2), Instruction("???", self.xxx, self.imp, 2), Instruction("JMP", JMP, self.abs, 3), Instruction("EOR", EOR, self.abs, 4), Instruction("LSR", LSR, self.abs, 6), Instruction("???", self.xxx, self.imp, 6),
            Instruction("BVC", self.bvc, self.rel, 2), Instruction("EOR", EOR, self.izy, 5), Instruction("???", self.xxx, self.imp, 2), Instruction("???", self.xxx, self.imp, 8), Instruction("???", NOP, self.imp, 4), Instruction("EOR", EOR, self.zpx, 4), Instruction("LSR", LSR, self.zpx, 6), Instruction("???", self.xxx, self.imp, 6), Instruction("CLI", CLI, self.imp, 2), Instruction("EOR", EOR, self.aby, 4), Instruction("???", NOP, self.imp, 2), Instruction("???", self.xxx, self.imp, 7), Instruction("???", NOP, self.imp, 4), Instruction("EOR", EOR, self.abx, 4), Instruction("LSR", LSR, self.abx, 7), Instruction("???", self.xxx, self.imp, 7),
            Instruction("RTS", self.rts, self.imp, 6), Instruction("ADC", ADC, self.izx, 6), Instruction("???", self.xxx, self.imp, 2), Instruction("???", self.xxx, self.imp, 8), Instruction("???", NOP, self.imp, 3), Instruction("ADC", ADC, self.zp0, 3), Instruction("ROR", ROR, self.zp0, 5), Instruction("???", self.xxx, self.imp, 5), Instruction("PLA", PLA, self.imp, 4), Instruction("ADC", ADC, self.imp, 2), Instruction("ROR", ROR, self.imp, 2), Instruction("???", self.xxx, self.imp, 2), Instruction("JMP", JMP, IND, 5), Instruction("ADC", ADC, self.abs, 4), Instruction("ROR", ROR, self.abs, 6), Instruction("???", self.xxx, self.imp, 6),
            Instruction("BVS", self.bvs, self.rel, 2), Instruction("ADC", ADC, self.izy, 5), Instruction("???", self.xxx, self.imp, 2), Instruction("???", self.xxx, self.imp, 8), Instruction("???", NOP, self.imp, 4), Instruction("ADC", ADC, self.zpx, 4), Instruction("ROR", ROR, self.zpx, 6), Instruction("???", self.xxx, self.imp, 6), Instruction("SEI", SEI, self.imp, 2), Instruction("ADC", ADC, self.aby, 4), Instruction("???", NOP, self.imp, 2), Instruction("???", self.xxx, self.imp, 7), Instruction("???", NOP, self.imp, 4), Instruction("ADC", ADC, self.abx, 4), Instruction("ROR", ROR, self.abx, 7), Instruction("???", self.xxx, self.imp, 7),
            Instruction("???", self.nop, self.imp, 2), Instruction("STA", STA, self.izx, 6), Instruction("???", NOP, self.imp, 2), Instruction("???", self.xxx, self.imp, 6), Instruction("STY", STY, self.zp0, 3), Instruction("STA", STA, self.zp0, 3), Instruction("STX", STX, self.zp0, 3), Instruction("???", self.xxx, self.imp, 3), Instruction("DEY", DEY, self.imp, 2), Instruction("???", NOP, self.imp, 2), Instruction("TXA", TXA, self.imp, 2), Instruction("???", self.xxx, self.imp, 2), Instruction("STY", STY, self.abs, 4), Instruction("STA", STA, self.abs, 4), Instruction("STX", STX, self.abs, 4), Instruction("???", self.xxx, self.imp, 4),
            Instruction("BCC", self.bcc, self.rel, 2), Instruction("STA", STA, self.izy, 6), Instruction("???", self.xxx, self.imp, 2), Instruction("???", self.xxx, self.imp, 6), Instruction("STY", STY, self.zpx, 4), Instruction("STA", STA, self.zpx, 4), Instruction("STX", STX, self.zpy, 4), Instruction("???", self.xxx, self.imp, 4), Instruction("TYA", TYA, self.imp, 2), Instruction("STA", STA, self.aby, 5), Instruction("TXS", TXS, self.imp, 2), Instruction("???", self.xxx, self.imp, 5), Instruction("???", NOP, self.imp, 5), Instruction("STA", STA, self.abx, 5), Instruction("???", self.xxx, self.imp, 5), Instruction("???", self.xxx, self.imp, 5),
            Instruction("LDY", self.ldy, self.imp, 2), Instruction("LDA", LDA, self.izx, 6), Instruction("LDX", LDX, self.imp, 2), Instruction("???", self.xxx, self.imp, 6), Instruction("LDY", LDY, self.zp0, 3), Instruction("LDA", LDA, self.zp0, 3), Instruction("LDX", LDX, self.zp0, 3), Instruction("???", self.xxx, self.imp, 3), Instruction("TAY", TAY, self.imp, 2), Instruction("LDA", LDA, self.imp, 2), Instruction("TAX", TAX, self.imp, 2), Instruction("???", self.xxx, self.imp, 2), Instruction("LDY", LDY, self.abs, 4), Instruction("LDA", LDA, self.abs, 4), Instruction("LDX", LDX, self.abs, 4), Instruction("???", self.xxx, self.imp, 4),
            Instruction("BCS", self.bcs, self.rel, 2), Instruction("LDA", LDA, self.izy, 5), Instruction("???", self.xxx, self.imp, 2), Instruction("???", self.xxx, self.imp, 5), Instruction("LDY", LDY, self.zpx, 4), Instruction("LDA", LDA, self.zpx, 4), Instruction("LDX", LDX, self.zpy, 4), Instruction("???", self.xxx, self.imp, 4), Instruction("CLV", CLV, self.imp, 2), Instruction("LDA", LDA, self.aby, 4), Instruction("TSX", TSX, self.imp, 2), Instruction("???", self.xxx, self.imp, 4), Instruction("LDY", LDY, self.abx, 4), Instruction("LDA", LDA, self.abx, 4), Instruction("LDX", LDX, self.aby, 4), Instruction("???", self.xxx, self.imp, 4),
            Instruction("CPY", self.cpy, self.imp, 2), Instruction("CMP", CMP, self.izx, 6), Instruction("???", NOP, self.imp, 2), Instruction("???", self.xxx, self.imp, 8), Instruction("CPY", CPY, self.zp0, 3), Instruction("CMP", CMP, self.zp0, 3), Instruction("DEC", DEC, self.zp0, 5), Instruction("???", self.xxx, self.imp, 5), Instruction("INY", INY, self.imp, 2), Instruction("CMP", CMP, self.imp, 2), Instruction("DEX", DEX, self.imp, 2), Instruction("???", self.xxx, self.imp, 2), Instruction("CPY", CPY, self.abs, 4), Instruction("CMP", CMP, self.abs, 4), Instruction("DEC", DEC, self.abs, 6), Instruction("???", self.xxx, self.imp, 6),
            Instruction("BNE", self.bne, self.rel, 2), Instruction("CMP", CMP, self.izy, 5), Instruction("???", self.xxx, self.imp, 2), Instruction("???", self.xxx, self.imp, 8), Instruction("???", NOP, self.imp, 4), Instruction("CMP", CMP, self.zpx, 4), Instruction("DEC", DEC, self.zpx, 6), Instruction("???", self.xxx, self.imp, 6), Instruction("CLD", CLD, self.imp, 2), Instruction("CMP", CMP, self.aby, 4), Instruction("NOP", NOP, self.imp, 2), Instruction("???", self.xxx, self.imp, 7), Instruction("???", NOP, self.imp, 4), Instruction("CMP", CMP, self.abx, 4), Instruction("DEC", DEC, self.abx, 7), Instruction("???", self.xxx, self.imp, 7),
            Instruction("CPX", self.cpx, self.imp, 2), Instruction("SBC", SBC, self.izx, 6), Instruction("???", NOP, self.imp, 2), Instruction("???", self.xxx, self.imp, 8), Instruction("CPX", CPX, self.zp0, 3), Instruction("SBC", SBC, self.zp0, 3), Instruction("INC", INC, self.zp0, 5), Instruction("???", self.xxx, self.imp, 5), Instruction("INX", INX, self.imp, 2), Instruction("SBC", SBC, self.imp, 2), Instruction("NOP", NOP, self.imp, 2), Instruction("???", SBC, self.imp, 2), Instruction("CPX", CPX, self.abs, 4), Instruction("SBC", SBC, self.abs, 4), Instruction("INC", INC, self.abs, 6), Instruction("???", self.xxx, self.imp, 6),
            Instruction("BEQ", self.beq, self.rel, 2), Instruction("SBC", SBC, self.izy, 5), Instruction("???", self.xxx, self.imp, 2), Instruction("???", self.xxx, self.imp, 8), Instruction("???", NOP, self.imp, 4), Instruction("SBC", SBC, self.zpx, 4), Instruction("INC", INC, self.zpx, 6), Instruction("???", self.xxx, self.imp, 6), Instruction("SED", SED, self.imp, 2), Instruction("SBC", SBC, self.aby, 4), Instruction("NOP", NOP, self.imp, 2), Instruction("???", self.xxx, self.imp, 7), Instruction("???", NOP, self.imp, 4), Instruction("SBC", SBC, self.abx, 4), Instruction("INC", INC, self.abx, 7), Instruction("???", self.xxx, self.imp, 7),
        ]
        return instruction_list